# Generated by Django 5.2.12 on 2026-03-26 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('teacher', 'Учитель'), ('student', 'Ученик')], default='teacher', max_length=16)),
                ('patronymic', models.CharField(blank=True, max_length=150)),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/')),
                ('teacher_subject', models.CharField(blank=True, max_length=150)),
                ('teacher_status', models.CharField(blank=True, max_length=255)),
                ('student_classroom', models.CharField(blank=True, max_length=64)),
                ('student_status', models.CharField(blank=True, choices=[('готов учиться!', 'готов учиться!'), ('хочу спать...', 'хочу спать...'), ('скорей бы домой!', 'скорей бы домой!'), ('главный решатель квизов!', 'главный решатель квизов!'), ('№1 в своём классе!', '№1 в своём классе!')], max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user__username',),
            },
        ),
    ]
