# Generated by Django 5.2.12 on 2026-03-26 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysession',
            name='participant_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activitysession',
            name='status',
            field=models.CharField(choices=[('started', 'Начато'), ('completed', 'Завершено'), ('abandoned', 'Прервано')], default='started', max_length=16),
        ),
    ]
